// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtZWnxuwjHB6WAQjWttSccDdblQsvcxQo',
    appId: '1:596339198290:web:673928336ff1874d82d28b',
    messagingSenderId: '596339198290',
    projectId: 'qr-scanner-app-1be57',
    authDomain: 'qr-scanner-app-1be57.firebaseapp.com',
    storageBucket: 'qr-scanner-app-1be57.firebasestorage.app',
    measurementId: 'G-QVF07BC4B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAckMwWMIrMSseebGS3B8rfTHJ1VncQHcs',
    appId: '1:596339198290:android:82ab6f5ad0612d3f82d28b',
    messagingSenderId: '596339198290',
    projectId: 'qr-scanner-app-1be57',
    storageBucket: 'qr-scanner-app-1be57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkaaDpdfm5xWYKC1FdIqYzE7Ey4cGDWoY',
    appId: '1:596339198290:ios:1668c046f0f038dc82d28b',
    messagingSenderId: '596339198290',
    projectId: 'qr-scanner-app-1be57',
    storageBucket: 'qr-scanner-app-1be57.firebasestorage.app',
    iosBundleId: 'com.example.qrScannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkaaDpdfm5xWYKC1FdIqYzE7Ey4cGDWoY',
    appId: '1:596339198290:ios:1668c046f0f038dc82d28b',
    messagingSenderId: '596339198290',
    projectId: 'qr-scanner-app-1be57',
    storageBucket: 'qr-scanner-app-1be57.firebasestorage.app',
    iosBundleId: 'com.example.qrScannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtZWnxuwjHB6WAQjWttSccDdblQsvcxQo',
    appId: '1:596339198290:web:18d9e1b3b711b32a82d28b',
    messagingSenderId: '596339198290',
    projectId: 'qr-scanner-app-1be57',
    authDomain: 'qr-scanner-app-1be57.firebaseapp.com',
    storageBucket: 'qr-scanner-app-1be57.firebasestorage.app',
    measurementId: 'G-4GP18NKBDB',
  );
}
